CREATE TABLE USERS
(ID INTEGER  NOT NULL AUTO_INCREMENT,
USERNAME VARCHAR(20) NOT NULL,
PASSWORD CHAR(256)) NOT NULL;

CREATE TABLE NATIONS
(ID INTEGER NOT NULL, 
INFRASTRUCTURE DECIMAL(10,2), 
TECHNOLOGY DECIMAL(10,2),  
LAND DECIMAL(10,2),
RESOURCE_1 VARCHAR(10),
RESOURCE_2 VARCHAR(10),
PRIMARY KEY (ID),
FOREIGN KEY (ID) REFERENCES USERS (ID));

CREATE TABLE WARS 
(ID_ATTACKER INTEGER NOT NULL, 
ID_DEFENDER INTEGER NOT NULL, 
START_DATE DATE, 
PRIMARY KEY (ID_ATTACKER, ID_DEFENDER),
FOREIGN KEY (ID_ATTACKER) references USERS (ID),
FOREIGN KEY (ID_DEFENDER) references USERS (ID));

CREATE TABLE TRADES 
(ID_INITIATOR INTEGER NOT NULL, 
ID_RECIEVER INTEGER NOT NULL, 
START_DATE DATE, 
PRIMARY KEY (ID_INITIATOR, ID_RECIEVER),
FOREIGN KEY (ID_INITIATOR) references USERS (ID),
FOREIGN KEY (ID_RECIEVER) references USERS (ID));
